save_strategy: "steps"
evaluation_strategy: "steps"
learning_rate: 2e-5
per_device_train_batch_size: 16
per_device_eval_batch_size: 32
num_train_epochs: 2
warmup_steps: 5000
logging_steps: 5000
save_steps: 5000
weight_decay: 0.01
push_to_hub: False